subscription GlobalMostRecent {
  Beam(
    order_by: { lastUpdated: desc }
    limit: 20
    where: { beamPool: { active: { _eq: true } } }
  ) {
    id
    units
    lastUpdated
    beamPool {
      flowRate
      totalUnits
    }
    from {
      fid
      id
    }
    to {
      fid
      id
    }
  }
}

subscription GlobalTop {
  BeamPool(
    order_by: { flowRate: desc_nulls_last }
    limit: 20
    where: { active: { _eq: true } }
  ) {
    id
    flowRate
    totalUnits
    creatorAccount {
      user {
        fid
        # profile {
        #   pfp_url
        #   username
        #   display_name
        # }
      }
    }
  }
}
