subscription LoggedInUser($id: String!) {
  User_by_pk(id: $id) {
    id
    pools(where: { isActive: { _eq: true } }) {
      id
    }
    incoming {
      id
      units
      beamPool {
        flowRate
        totalUnits
      }
      from {
        fid
        id
        profile {
          id
          pfp_url
          display_name
          username
          id
        }
      }
    }
    outgoing {
      units
      id
      beamPool {
        flowRate
        totalUnits
      }
      to {
        id
        fid
        profile {
          id
          display_name
          username
          pfp_url
          id
        }
      }
    }
  }
}
