subscription LoggedInUser($id: String!) {
  User_by_pk(id: $id) {
    id
    pools {
      id
    }
    incoming(
      order_by: { lastUpdated: desc }
      where: { beamPool: { active: { _eq: true } } }
    ) {
      id
      units
      lastUpdated
      beamPool {
        flowRate
        totalUnits
        id
      }
      from {
        fid
        id
        profile {
          id
          pfp_url
          display_name
          username
          id
        }
      }
    }
    outgoing(
      order_by: { lastUpdated: desc }
      where: { beamPool: { active: { _eq: true } } }
    ) {
      units
      id
      beamPool {
        flowRate
        totalUnits
        id
      }
      to {
        id
        fid
        profile {
          id
          display_name
          username
          pfp_url
          id
        }
      }
    }
  }
}
